services:
  crew:
    build:
      context: .
      dockerfile: Dockerfile
      cache_from:
        - crewai_template:0.1.0
    image: crewai_template:0.1.0
    volumes:
      - ./src:/app/src
      - ./report.md:/app/report.md
      - pip-cache:/root/.cache/pip
    env_file:
      - .env
    environment:
      - PYTHONPATH=/app/src

volumes:
  pip-cache:
    name: pip-cache
