services:
  crew:
    build:
      context: .
      dockerfile: Dockerfile
      cache_from:
        - crewai_template:0.1.0
    image: crewai_template:0.1.0
    volumes:
      - ./src:/app/src
      - ./knowledge:/app/knowledge
    env_file:
      - .env
    environment:
      - PYTHONPATH=/app/src
